language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TARGET=cs_dry_run
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.4
      env: DEPENDENCIES="symfony/flex" SYMFONY_VERSION="^3.4"
    - php: 7.4
      env: DEPENDENCIES="symfony/flex" SYMFONY_VERSION="^4.4"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if ! [ -z "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;
  - if ! [ -z "$SYMFONY_VERSION" ]; then composer config extra.symfony.require ${SYMFONY_VERSION}; fi

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - make $TARGET
